CREATE TABLE "users" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar(100) NOT NULL,
                         "email" varchar(100) UNIQUE NOT NULL,
                         "username" varchar(50) UNIQUE NOT NULL,
                         "password_hash" varchar NOT NULL,
                         "phone" varchar NOT NULL,
                         "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         "role_id" int NOT NULL,
                         "active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "customers" (
                             "customer_id" int PRIMARY KEY,
                             "total_bookings" int NOT NULL,
                             "total_spent" bigint NOT NULL,
                             "loyalty_level" varchar(10) NOT NULL
);

CREATE TABLE "employees" (
                             "employee_id" int PRIMARY KEY,
                             "employee_code" varchar(10) UNIQUE NOT NULL,
                             "address" varchar NOT NULL,
                             "date_of_birth" date NOT NULL,
                             "gender" varchar(10),
                             "salary" int NOT NULL
);

CREATE TABLE "roles" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar(50) NOT NULL
);

CREATE TABLE "actions" (
                           "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "name" varchar(50) NOT NULL
);

CREATE TABLE "role_action" (
                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "create" smallint NOT NULL,
                               "read" smallint NOT NULL,
                               "update" smallint NOT NULL,
                               "delete" smallint NOT NULL,
                               "role_id" int NOT NULL,
                               "action_id" int NOT NULL
);

CREATE TABLE "courts" (
                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "name" varchar NOT NULL,
                          "location" varchar NOT NULL,
                          "description" varchar NOT NULL,
                          "court_quantity" smallint NOT NULL,
                          "status" boolean NOT NULL DEFAULT true
);

CREATE TABLE "court_schedules" (
                                   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "court_id" int NOT NULL,
                                   "day_of_week" smallint NOT NULL,
                                   "open_time" time,
                                   "close_time" time
);

CREATE TABLE "time_slots" (
                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "start_time" timestamp NOT NULL,
                              "end_time" timestamp NOT NULL
);

CREATE TABLE "holidays" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "holiday_date" date NOT NULL,
                            "name" varchar(50) NOT NULL
);

CREATE TABLE "price_rules" (
                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "court_id" int NOT NULL,
                               "day_type" varchar(10) NOT NULL,
                               "time_slot_id" int NOT NULL,
                               "price" int NOT NULL
);

CREATE TABLE "court_reviews" (
                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "court_id" int NOT NULL,
                                 "customer_id" int NOT NULL,
                                 "booking_id" int UNIQUE NOT NULL,
                                 "rating" smallint NOT NULL,
                                 "comment" text,
                                 "create_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 "update_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "review_media" (
                                "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "review_id" int NOT NULL,
                                "media_type" varchar(10) NOT NULL,
                                "media_url" varchar NOT NULL,
                                "thumbnail_url" varchar,
                                "sort_order" smallint NOT NULL,
                                "create_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "bookings" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "user_id" int,
                            "booking_date" timestamp,
                            "status" varchar(10) NOT NULL,
                            "subtotal_amount" int NOT NULL,
                            "discount_amount" int NOT NULL,
                            "total_amount" int NOT NULL,
                            "create_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "booking_details" (
                                   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "court_id" int NOT NULL,
                                   "booking_id" int NOT NULL,
                                   "time_slot_id" int NOT NULL,
                                   "total" int NOT NULL
);

CREATE TABLE "services" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar(100) NOT NULL,
                            "type" varchar(10) NOT NULL,
                            "price" int NOT NULL,
                            "unit" smallint NOT NULL,
                            "status" boolean NOT NULL DEFAULT true,
                            "has_inventory" boolean NOT NULL DEFAULT true
);

CREATE TABLE "service_inventories" (
                                       "service_id" int PRIMARY KEY,
                                       "quantity_available" int NOT NULL,
                                       "quantity_total" int NOT NULL
);

CREATE TABLE "booking_services" (
                                    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "booking_id" int NOT NULL,
                                    "service_id" int NOT NULL,
                                    "quantity" smallint NOT NULL,
                                    "price_at_time" int NOT NULL
);

CREATE TABLE "promotions" (
                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "voucher_code" varchar(20) NOT NULL,
                              "description" varchar(100) NOT NULL,
                              "type" varchar(10) NOT NULL,
                              "value" smallint NOT NULL,
                              "min_booking_amount" smallint NOT NULL,
                              "loyalty_level_required" varchar(10) NOT NULL,
                              "usage" int NOT NULL,
                              "start_date" timestamp NOT NULL,
                              "end_date" timestamp NOT NULL,
                              "status" boolean NOT NULL DEFAULT true
);

CREATE TABLE "booking_promotions" (
                                      "booking_id" int NOT NULL,
                                      "promotion_id" int NOT NULL,
                                      "discount_amount" int NOT NULL
);

CREATE TABLE "payments" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "booking_id" int NOT NULL,
                            "amount" int NOT NULL,
                            "method" varchar(10) NOT NULL,
                            "status" varchar(10) NOT NULL,
                            "paid_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "work_shifts" (
                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "name" varchar(20) NOT NULL,
                               "start_time" time NOT NULL,
                               "end_time" time NOT NULL,
                               "status" boolean NOT NULL DEFAULT true,
                               "salary_per_shift" int NOT NULL
);

CREATE TABLE "employee_shifts" (
                                   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "employee_id" int,
                                   "court_id" int NOT NULL,
                                   "work_shift_id" int,
                                   "shift_date" date NOT NULL,
                                   "status" varchar(10) NOT NULL
);

COMMENT ON TABLE "users" IS 'This table is the root for all accounts';

COMMENT ON COLUMN "users"."password_hash" IS 'encrypted password';

COMMENT ON TABLE "customers" IS 'This table represents for customers use the system';

COMMENT ON COLUMN "customers"."loyalty_level" IS 'bronze, silver, gold, diamond';

COMMENT ON TABLE "employees" IS 'This table represents for employees work for the system';

COMMENT ON TABLE "roles" IS 'This table divides different roles by users';

COMMENT ON TABLE "actions" IS 'This table defines all functions users have';

COMMENT ON TABLE "role_action" IS 'This table shows the action per role can work';

COMMENT ON TABLE "courts" IS 'This table gives information about a court';

COMMENT ON TABLE "court_schedules" IS 'This table sets open time and close time of the court';

COMMENT ON TABLE "time_slots" IS 'This table manages the courts schedule for customers book';

COMMENT ON TABLE "holidays" IS 'This table adds holiday time to apply court price.';

COMMENT ON TABLE "price_rules" IS 'This table sets the booking price based on holiday or weekend';

COMMENT ON COLUMN "price_rules"."day_type" IS 'Weekday, Weekend, Holiday';

COMMENT ON COLUMN "court_reviews"."rating" IS '1-5 star';

COMMENT ON COLUMN "review_media"."media_type" IS 'image, video';

COMMENT ON COLUMN "review_media"."thumbnail_url" IS 'Only for video';

COMMENT ON COLUMN "review_media"."sort_order" IS 'the order of media displays in review';

COMMENT ON TABLE "bookings" IS 'This table stores booking information of customers';

COMMENT ON COLUMN "bookings"."status" IS 'pending / confirmed / cancelled';

COMMENT ON TABLE "booking_details" IS 'This table shows more information about the court booking.';

COMMENT ON TABLE "services" IS 'This table adds add-on service besides booking the court';

COMMENT ON COLUMN "services"."type" IS 'drinks, foods, rental';

COMMENT ON COLUMN "services"."unit" IS 'hour, item';

COMMENT ON TABLE "service_inventories" IS 'This table manages the service inventories';

COMMENT ON TABLE "booking_services" IS 'This table applies add-on services into booking of customers';

COMMENT ON TABLE "promotions" IS 'This table adds voucher to discount price';

COMMENT ON COLUMN "promotions"."type" IS 'fixed, percent';

COMMENT ON COLUMN "promotions"."usage" IS 'Usage voucher maximum times';

COMMENT ON TABLE "booking_promotions" IS 'This table applies promotion voucher to booking';

COMMENT ON TABLE "payments" IS 'This table stores the payment information about booking';

COMMENT ON COLUMN "payments"."status" IS 'pending, success, failure';

COMMENT ON TABLE "work_shifts" IS 'This table defines work shifts for employees in each court';

COMMENT ON COLUMN "work_shifts"."name" IS 'Morning, Afternoon, Night';

COMMENT ON TABLE "employee_shifts" IS 'This table divines shifts for employees';

COMMENT ON COLUMN "employee_shifts"."status" IS 'assigned, completed, canceled';

ALTER TABLE "customers" ADD FOREIGN KEY ("customer_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employees" ADD FOREIGN KEY ("employee_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_action" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_action" ADD FOREIGN KEY ("action_id") REFERENCES "actions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "court_schedules" ADD FOREIGN KEY ("court_id") REFERENCES "courts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "price_rules" ADD FOREIGN KEY ("court_id") REFERENCES "courts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "price_rules" ADD FOREIGN KEY ("time_slot_id") REFERENCES "time_slots" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "court_reviews" ADD FOREIGN KEY ("court_id") REFERENCES "courts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "court_reviews" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "review_media" ADD FOREIGN KEY ("review_id") REFERENCES "court_reviews" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "court_reviews" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "booking_details" ADD FOREIGN KEY ("court_id") REFERENCES "courts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "booking_details" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "booking_details" ADD FOREIGN KEY ("time_slot_id") REFERENCES "time_slots" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "service_inventories" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "booking_services" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "booking_services" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "booking_promotions" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "booking_promotions" ADD FOREIGN KEY ("promotion_id") REFERENCES "promotions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employee_shifts" ADD FOREIGN KEY ("work_shift_id") REFERENCES "work_shifts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employee_shifts" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employee_shifts" ADD FOREIGN KEY ("court_id") REFERENCES "courts" ("id") DEFERRABLE INITIALLY IMMEDIATE;