spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/badminton_scheduling_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:phu}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:phu}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
# M?c ??nh local không dùng SSL. Khi lên AWS, docker run truy?n true vào s? ghi ?è.
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL_ENABLED:false}