spring.application.name=backend

server.port=8080
# set vietnamese time in logs
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# CONFIG DATABASE (postgresql)
# use environment variables in production and localhost in dev

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/badminton_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:phu}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:phu}
spring.datasource.driver-class-name=org.postgresql.Driver


# CONFIG HIBERNATE & FLYWAY

spring.flyway.enabled=true
# allow Hibernate check (validate) entity structure, not edit the table
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

# see hibernate log for debug and local
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# CONFIG REDIS

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL_ENABLED:false}